spring:
    application:
        name: account-client
    liquibase:
        enabled: true
        change-log: classpath:db/changelog-master.yml
        default-schema: public
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://pilot-postgres-1:5432/postgres
        username: postgres
        password: postgres

server:
    port: 8081

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://pilot-eureka-server-1:8761/eureka}
    instance:
        preferIpAddress: true
