version: "3.9"

networks:
  app-network:
    name: app-network
    driver: bridge

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - app-network  # Подключаем сервис к созданной сети

  eureka-server:
    image: eureka-server:latest
    build: eureka-server
    restart: "no"
    ports:
      - "8761:8761"
    networks:
      - app-network

  gateway:
    image: gateway:latest
    build: gateway
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - app-network

  account-client:
    image: account-client:latest
    build: account-client
    restart: "no"
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server
      - gateway
    networks:
      - app-network
      
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.2.1
#    hostname: zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000

#  kafka:
#    image: confluentinc/cp-server:7.2.1
#    hostname: kafka
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#      - "9997:9997"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_JMX_PORT: 9997
#      KAFKA_JMX_HOSTNAME: kafka
#
#  kafka-ui:
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - "8082:8080"
#    environment:
#      DYNAMIC_CONFIG_ENABLED: true
