spring:
    application:
        name: gateway
    security:
        user:
            password: qwerty

server:
    port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI}

logging:
    pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"